/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface CandidateStorageInterface extends utils.Interface {
  functions: {
    "candidate()": FunctionFragment;
    "committee()": FunctionFragment;
    "isLayer2Candidate()": FunctionFragment;
    "memo()": FunctionFragment;
    "seigManager()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "candidate"
      | "committee"
      | "isLayer2Candidate"
      | "memo"
      | "seigManager"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "candidate", values?: undefined): string;
  encodeFunctionData(functionFragment: "committee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isLayer2Candidate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "memo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "seigManager",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "candidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "committee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLayer2Candidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "memo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "seigManager",
    data: BytesLike
  ): Result;

  events: {};
}

export interface CandidateStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CandidateStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    candidate(overrides?: CallOverrides): Promise<[string]>;

    committee(overrides?: CallOverrides): Promise<[string]>;

    isLayer2Candidate(overrides?: CallOverrides): Promise<[boolean]>;

    memo(overrides?: CallOverrides): Promise<[string]>;

    seigManager(overrides?: CallOverrides): Promise<[string]>;
  };

  candidate(overrides?: CallOverrides): Promise<string>;

  committee(overrides?: CallOverrides): Promise<string>;

  isLayer2Candidate(overrides?: CallOverrides): Promise<boolean>;

  memo(overrides?: CallOverrides): Promise<string>;

  seigManager(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    candidate(overrides?: CallOverrides): Promise<string>;

    committee(overrides?: CallOverrides): Promise<string>;

    isLayer2Candidate(overrides?: CallOverrides): Promise<boolean>;

    memo(overrides?: CallOverrides): Promise<string>;

    seigManager(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    candidate(overrides?: CallOverrides): Promise<BigNumber>;

    committee(overrides?: CallOverrides): Promise<BigNumber>;

    isLayer2Candidate(overrides?: CallOverrides): Promise<BigNumber>;

    memo(overrides?: CallOverrides): Promise<BigNumber>;

    seigManager(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    candidate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    committee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isLayer2Candidate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    memo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    seigManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
