/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface SeigManagerV1_3Interface extends utils.Interface {
  functions: {
    "BURNT_AMOUNT_MAINNET()": FunctionFragment;
    "CHALLENGER_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "INITIAL_TOTAL_SUPPLY_MAINNET()": FunctionFragment;
    "MAX_VALID_COMMISSION()": FunctionFragment;
    "MINTER_ROLE()": FunctionFragment;
    "MIN_VALID_COMMISSION()": FunctionFragment;
    "OPERATOR_ROLE()": FunctionFragment;
    "PAUSE_ROLE()": FunctionFragment;
    "RAY()": FunctionFragment;
    "SEIG_START_MAINNET()": FunctionFragment;
    "accRelativeSeig()": FunctionFragment;
    "addAdmin(address)": FunctionFragment;
    "addChallenger(address)": FunctionFragment;
    "addMinter(address)": FunctionFragment;
    "addOperator(address)": FunctionFragment;
    "adjustCommissionDelay()": FunctionFragment;
    "aliveImplementation(address)": FunctionFragment;
    "allowIssuanceLayer2Seigs(address)": FunctionFragment;
    "burntAmountAtDAO()": FunctionFragment;
    "dao()": FunctionFragment;
    "daoSeigRate()": FunctionFragment;
    "delayedCommissionBlock(address)": FunctionFragment;
    "delayedCommissionRate(address)": FunctionFragment;
    "delayedCommissionRateNegative(address)": FunctionFragment;
    "estimatedDistribute(uint256,address,bool)": FunctionFragment;
    "excludeFromSeigniorage(address)": FunctionFragment;
    "factory()": FunctionFragment;
    "getOperatorAmount(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialTotalSupply()": FunctionFragment;
    "isAdmin(address)": FunctionFragment;
    "isChallenger(address)": FunctionFragment;
    "isMinter(address)": FunctionFragment;
    "isOperator(address)": FunctionFragment;
    "isOwner()": FunctionFragment;
    "l2Registry()": FunctionFragment;
    "l2RewardPerUint()": FunctionFragment;
    "lastSnapshotId()": FunctionFragment;
    "layer2Manager()": FunctionFragment;
    "layer2RewardInfo(address)": FunctionFragment;
    "layer2StartBlock()": FunctionFragment;
    "minimumAmount()": FunctionFragment;
    "pauseProxy()": FunctionFragment;
    "paused()": FunctionFragment;
    "powerTONSeigRate()": FunctionFragment;
    "proxyImplementation(uint256)": FunctionFragment;
    "relativeSeigRate()": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "removeChallenger(address)": FunctionFragment;
    "removeMinter(address)": FunctionFragment;
    "removeOperator(address)": FunctionFragment;
    "renounceChallenger()": FunctionFragment;
    "renounceMinter()": FunctionFragment;
    "renounceOperator()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeChallenger(address)": FunctionFragment;
    "revokeMinter(address)": FunctionFragment;
    "revokeOperator(address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "seigStartBlock()": FunctionFragment;
    "selectorImplementation(bytes4)": FunctionFragment;
    "setL2Registry(address)": FunctionFragment;
    "setLayer2Manager(address)": FunctionFragment;
    "setLayer2StartBlock(uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "totalLayer2TVL()": FunctionFragment;
    "totalSupplyOfTon()": FunctionFragment;
    "transferAdmin(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unSettledReward(address)": FunctionFragment;
    "updateSeigniorage()": FunctionFragment;
    "updateSeigniorageLayer(address)": FunctionFragment;
    "updateSeigniorageOperator()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BURNT_AMOUNT_MAINNET"
      | "CHALLENGER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INITIAL_TOTAL_SUPPLY_MAINNET"
      | "MAX_VALID_COMMISSION"
      | "MINTER_ROLE"
      | "MIN_VALID_COMMISSION"
      | "OPERATOR_ROLE"
      | "PAUSE_ROLE"
      | "RAY"
      | "SEIG_START_MAINNET"
      | "accRelativeSeig"
      | "addAdmin"
      | "addChallenger"
      | "addMinter"
      | "addOperator"
      | "adjustCommissionDelay"
      | "aliveImplementation"
      | "allowIssuanceLayer2Seigs"
      | "burntAmountAtDAO"
      | "dao"
      | "daoSeigRate"
      | "delayedCommissionBlock"
      | "delayedCommissionRate"
      | "delayedCommissionRateNegative"
      | "estimatedDistribute"
      | "excludeFromSeigniorage"
      | "factory"
      | "getOperatorAmount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialTotalSupply"
      | "isAdmin"
      | "isChallenger"
      | "isMinter"
      | "isOperator"
      | "isOwner"
      | "l2Registry"
      | "l2RewardPerUint"
      | "lastSnapshotId"
      | "layer2Manager"
      | "layer2RewardInfo"
      | "layer2StartBlock"
      | "minimumAmount"
      | "pauseProxy"
      | "paused"
      | "powerTONSeigRate"
      | "proxyImplementation"
      | "relativeSeigRate"
      | "removeAdmin"
      | "removeChallenger"
      | "removeMinter"
      | "removeOperator"
      | "renounceChallenger"
      | "renounceMinter"
      | "renounceOperator"
      | "renounceOwnership"
      | "renounceRole"
      | "revokeChallenger"
      | "revokeMinter"
      | "revokeOperator"
      | "revokeRole"
      | "seigStartBlock"
      | "selectorImplementation"
      | "setL2Registry"
      | "setLayer2Manager"
      | "setLayer2StartBlock"
      | "supportsInterface"
      | "totalLayer2TVL"
      | "totalSupplyOfTon"
      | "transferAdmin"
      | "transferOwnership"
      | "unSettledReward"
      | "updateSeigniorage"
      | "updateSeigniorageLayer"
      | "updateSeigniorageOperator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BURNT_AMOUNT_MAINNET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CHALLENGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_TOTAL_SUPPLY_MAINNET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VALID_COMMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VALID_COMMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SEIG_START_MAINNET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accRelativeSeig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addChallenger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addMinter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustCommissionDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aliveImplementation",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "allowIssuanceLayer2Seigs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "burntAmountAtDAO",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoSeigRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delayedCommissionBlock",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "delayedCommissionRate",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "delayedCommissionRateNegative",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "estimatedDistribute",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "excludeFromSeigniorage",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOperatorAmount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isChallenger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isMinter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "l2Registry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "l2RewardPerUint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastSnapshotId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "layer2Manager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "layer2RewardInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "layer2StartBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pauseProxy",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "powerTONSeigRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxyImplementation",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "relativeSeigRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeChallenger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMinter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceChallenger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceMinter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeChallenger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeMinter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "seigStartBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectorImplementation",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setL2Registry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLayer2Manager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLayer2StartBlock",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLayer2TVL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOfTon",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unSettledReward",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeigniorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeigniorageLayer",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeigniorageOperator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BURNT_AMOUNT_MAINNET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CHALLENGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_TOTAL_SUPPLY_MAINNET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VALID_COMMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VALID_COMMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PAUSE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SEIG_START_MAINNET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accRelativeSeig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addChallenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMinter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustCommissionDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aliveImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowIssuanceLayer2Seigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burntAmountAtDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoSeigRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delayedCommissionBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delayedCommissionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delayedCommissionRateNegative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimatedDistribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludeFromSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isChallenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMinter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "l2Registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "l2RewardPerUint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSnapshotId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layer2Manager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layer2RewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "layer2StartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pauseProxy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "powerTONSeigRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxyImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relativeSeigRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeChallenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceChallenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeChallenger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "seigStartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectorImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setL2Registry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLayer2Manager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLayer2StartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLayer2TVL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOfTon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unSettledReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSeigniorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSeigniorageLayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSeigniorageOperator",
    data: BytesLike
  ): Result;

  events: {
    "AddedSeigAtLayer(address,uint256,uint256,uint256,uint256)": EventFragment;
    "Comitted(address)": EventFragment;
    "CommitLog1(uint256,uint256,uint256,uint256)": EventFragment;
    "ExcludedFromSeigniorage(address,uint256,uint256)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SeigGiven(address,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "SeigGiven2(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedSeigAtLayer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Comitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CommitLog1"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExcludedFromSeigniorage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SeigGiven"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SeigGiven2"): EventFragment;
}

export interface AddedSeigAtLayerEventObject {
  layer2: string;
  seigs: BigNumber;
  operatorSeigs: BigNumber;
  nextTotalSupply: BigNumber;
  prevTotalSupply: BigNumber;
}
export type AddedSeigAtLayerEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber],
  AddedSeigAtLayerEventObject
>;

export type AddedSeigAtLayerEventFilter =
  TypedEventFilter<AddedSeigAtLayerEvent>;

export interface ComittedEventObject {
  layer2: string;
}
export type ComittedEvent = TypedEvent<[string], ComittedEventObject>;

export type ComittedEventFilter = TypedEventFilter<ComittedEvent>;

export interface CommitLog1EventObject {
  totalStakedAmount: BigNumber;
  totalSupplyOfWTON: BigNumber;
  prevTotalSupply: BigNumber;
  nextTotalSupply: BigNumber;
}
export type CommitLog1Event = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  CommitLog1EventObject
>;

export type CommitLog1EventFilter = TypedEventFilter<CommitLog1Event>;

export interface ExcludedFromSeigniorageEventObject {
  layer2: string;
  layer2Tvl: BigNumber;
  initialDebt: BigNumber;
}
export type ExcludedFromSeigniorageEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ExcludedFromSeigniorageEventObject
>;

export type ExcludedFromSeigniorageEventFilter =
  TypedEventFilter<ExcludedFromSeigniorageEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface SeigGivenEventObject {
  layer2: string;
  totalSeig: BigNumber;
  stakedSeig: BigNumber;
  unstakedSeig: BigNumber;
  powertonSeig: BigNumber;
  daoSeig: BigNumber;
  pseig: BigNumber;
}
export type SeigGivenEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  SeigGivenEventObject
>;

export type SeigGivenEventFilter = TypedEventFilter<SeigGivenEvent>;

export interface SeigGiven2EventObject {
  layer2: string;
  totalSeig: BigNumber;
  stakedSeig: BigNumber;
  unstakedSeig: BigNumber;
  powertonSeig: BigNumber;
  daoSeig: BigNumber;
  pseig: BigNumber;
  l2TotalSeigs: BigNumber;
  layer2Seigs: BigNumber;
}
export type SeigGiven2Event = TypedEvent<
  [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  SeigGiven2EventObject
>;

export type SeigGiven2EventFilter = TypedEventFilter<SeigGiven2Event>;

export interface SeigManagerV1_3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SeigManagerV1_3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BURNT_AMOUNT_MAINNET(overrides?: CallOverrides): Promise<[BigNumber]>;

    CHALLENGER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    INITIAL_TOTAL_SUPPLY_MAINNET(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MAX_VALID_COMMISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    MIN_VALID_COMMISSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<[string]>;

    RAY(overrides?: CallOverrides): Promise<[BigNumber]>;

    SEIG_START_MAINNET(overrides?: CallOverrides): Promise<[BigNumber]>;

    accRelativeSeig(overrides?: CallOverrides): Promise<[BigNumber]>;

    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    adjustCommissionDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    aliveImplementation(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    allowIssuanceLayer2Seigs(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { systemConfig: string; allowed: boolean }>;

    burntAmountAtDAO(overrides?: CallOverrides): Promise<[BigNumber]>;

    dao(overrides?: CallOverrides): Promise<[string]>;

    daoSeigRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    delayedCommissionBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    delayedCommissionRate(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    delayedCommissionRateNegative(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    estimatedDistribute(
      blockNumber: PromiseOrValue<BigNumberish>,
      layer2: PromiseOrValue<string>,
      _isSenderOperator: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        maxSeig: BigNumber;
        stakedSeig: BigNumber;
        unstakedSeig: BigNumber;
        powertonSeig: BigNumber;
        daoSeig: BigNumber;
        relativeSeig: BigNumber;
        l2TotalSeigs: BigNumber;
        layer2Seigs: BigNumber;
      }
    >;

    excludeFromSeigniorage(
      _layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getOperatorAmount(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialTotalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    isAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    l2Registry(overrides?: CallOverrides): Promise<[string]>;

    l2RewardPerUint(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastSnapshotId(overrides?: CallOverrides): Promise<[BigNumber]>;

    layer2Manager(overrides?: CallOverrides): Promise<[string]>;

    layer2RewardInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { layer2Tvl: BigNumber; initialDebt: BigNumber }
    >;

    layer2StartBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    minimumAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    pauseProxy(overrides?: CallOverrides): Promise<[boolean]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    powerTONSeigRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    proxyImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    relativeSeigRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceChallenger(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceMinter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    seigStartBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    selectorImplementation(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setL2Registry(
      l2Registry_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLayer2Manager(
      layer2Manager_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLayer2StartBlock(
      startBlock_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    totalLayer2TVL(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupplyOfTon(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tos: BigNumber }>;

    transferAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unSettledReward(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    updateSeigniorage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSeigniorageLayer(
      layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSeigniorageOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BURNT_AMOUNT_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

  CHALLENGER_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  INITIAL_TOTAL_SUPPLY_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

  MIN_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

  OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  PAUSE_ROLE(overrides?: CallOverrides): Promise<string>;

  RAY(overrides?: CallOverrides): Promise<BigNumber>;

  SEIG_START_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

  accRelativeSeig(overrides?: CallOverrides): Promise<BigNumber>;

  addAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addChallenger(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addMinter(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addOperator(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  adjustCommissionDelay(overrides?: CallOverrides): Promise<BigNumber>;

  aliveImplementation(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  allowIssuanceLayer2Seigs(
    layer2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, boolean] & { systemConfig: string; allowed: boolean }>;

  burntAmountAtDAO(overrides?: CallOverrides): Promise<BigNumber>;

  dao(overrides?: CallOverrides): Promise<string>;

  daoSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

  delayedCommissionBlock(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  delayedCommissionRate(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  delayedCommissionRateNegative(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  estimatedDistribute(
    blockNumber: PromiseOrValue<BigNumberish>,
    layer2: PromiseOrValue<string>,
    _isSenderOperator: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      maxSeig: BigNumber;
      stakedSeig: BigNumber;
      unstakedSeig: BigNumber;
      powertonSeig: BigNumber;
      daoSeig: BigNumber;
      relativeSeig: BigNumber;
      l2TotalSeigs: BigNumber;
      layer2Seigs: BigNumber;
    }
  >;

  excludeFromSeigniorage(
    _layer2: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getOperatorAmount(
    layer2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  isAdmin(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isChallenger(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isMinter(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOperator(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  l2Registry(overrides?: CallOverrides): Promise<string>;

  l2RewardPerUint(overrides?: CallOverrides): Promise<BigNumber>;

  lastSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

  layer2Manager(overrides?: CallOverrides): Promise<string>;

  layer2RewardInfo(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { layer2Tvl: BigNumber; initialDebt: BigNumber }
  >;

  layer2StartBlock(overrides?: CallOverrides): Promise<BigNumber>;

  minimumAmount(overrides?: CallOverrides): Promise<BigNumber>;

  pauseProxy(overrides?: CallOverrides): Promise<boolean>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  powerTONSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

  proxyImplementation(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  relativeSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

  removeAdmin(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeChallenger(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeMinter(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeOperator(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceChallenger(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceMinter(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOperator(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeChallenger(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeMinter(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeOperator(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  seigStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

  selectorImplementation(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  setL2Registry(
    l2Registry_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLayer2Manager(
    layer2Manager_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLayer2StartBlock(
    startBlock_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  totalLayer2TVL(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupplyOfTon(overrides?: CallOverrides): Promise<BigNumber>;

  transferAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unSettledReward(
    layer2: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateSeigniorage(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSeigniorageLayer(
    layer2: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSeigniorageOperator(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BURNT_AMOUNT_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    CHALLENGER_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    INITIAL_TOTAL_SUPPLY_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

    MIN_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<string>;

    RAY(overrides?: CallOverrides): Promise<BigNumber>;

    SEIG_START_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    accRelativeSeig(overrides?: CallOverrides): Promise<BigNumber>;

    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    adjustCommissionDelay(overrides?: CallOverrides): Promise<BigNumber>;

    aliveImplementation(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    allowIssuanceLayer2Seigs(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, boolean] & { systemConfig: string; allowed: boolean }>;

    burntAmountAtDAO(overrides?: CallOverrides): Promise<BigNumber>;

    dao(overrides?: CallOverrides): Promise<string>;

    daoSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    delayedCommissionBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delayedCommissionRate(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delayedCommissionRateNegative(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    estimatedDistribute(
      blockNumber: PromiseOrValue<BigNumberish>,
      layer2: PromiseOrValue<string>,
      _isSenderOperator: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        maxSeig: BigNumber;
        stakedSeig: BigNumber;
        unstakedSeig: BigNumber;
        powertonSeig: BigNumber;
        daoSeig: BigNumber;
        relativeSeig: BigNumber;
        l2TotalSeigs: BigNumber;
        layer2Seigs: BigNumber;
      }
    >;

    excludeFromSeigniorage(
      _layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    factory(overrides?: CallOverrides): Promise<string>;

    getOperatorAmount(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    isAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    l2Registry(overrides?: CallOverrides): Promise<string>;

    l2RewardPerUint(overrides?: CallOverrides): Promise<BigNumber>;

    lastSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

    layer2Manager(overrides?: CallOverrides): Promise<string>;

    layer2RewardInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { layer2Tvl: BigNumber; initialDebt: BigNumber }
    >;

    layer2StartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    minimumAmount(overrides?: CallOverrides): Promise<BigNumber>;

    pauseProxy(overrides?: CallOverrides): Promise<boolean>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    powerTONSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    proxyImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    relativeSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceChallenger(overrides?: CallOverrides): Promise<void>;

    renounceMinter(overrides?: CallOverrides): Promise<void>;

    renounceOperator(overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    seigStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    selectorImplementation(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setL2Registry(
      l2Registry_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLayer2Manager(
      layer2Manager_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLayer2StartBlock(
      startBlock_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalLayer2TVL(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyOfTon(overrides?: CallOverrides): Promise<BigNumber>;

    transferAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unSettledReward(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateSeigniorage(overrides?: CallOverrides): Promise<boolean>;

    updateSeigniorageLayer(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    updateSeigniorageOperator(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AddedSeigAtLayer(address,uint256,uint256,uint256,uint256)"(
      layer2?: null,
      seigs?: null,
      operatorSeigs?: null,
      nextTotalSupply?: null,
      prevTotalSupply?: null
    ): AddedSeigAtLayerEventFilter;
    AddedSeigAtLayer(
      layer2?: null,
      seigs?: null,
      operatorSeigs?: null,
      nextTotalSupply?: null,
      prevTotalSupply?: null
    ): AddedSeigAtLayerEventFilter;

    "Comitted(address)"(
      layer2?: PromiseOrValue<string> | null
    ): ComittedEventFilter;
    Comitted(layer2?: PromiseOrValue<string> | null): ComittedEventFilter;

    "CommitLog1(uint256,uint256,uint256,uint256)"(
      totalStakedAmount?: null,
      totalSupplyOfWTON?: null,
      prevTotalSupply?: null,
      nextTotalSupply?: null
    ): CommitLog1EventFilter;
    CommitLog1(
      totalStakedAmount?: null,
      totalSupplyOfWTON?: null,
      prevTotalSupply?: null,
      nextTotalSupply?: null
    ): CommitLog1EventFilter;

    "ExcludedFromSeigniorage(address,uint256,uint256)"(
      layer2?: null,
      layer2Tvl?: null,
      initialDebt?: null
    ): ExcludedFromSeigniorageEventFilter;
    ExcludedFromSeigniorage(
      layer2?: null,
      layer2Tvl?: null,
      initialDebt?: null
    ): ExcludedFromSeigniorageEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "SeigGiven(address,uint256,uint256,uint256,uint256,uint256,uint256)"(
      layer2?: PromiseOrValue<string> | null,
      totalSeig?: null,
      stakedSeig?: null,
      unstakedSeig?: null,
      powertonSeig?: null,
      daoSeig?: null,
      pseig?: null
    ): SeigGivenEventFilter;
    SeigGiven(
      layer2?: PromiseOrValue<string> | null,
      totalSeig?: null,
      stakedSeig?: null,
      unstakedSeig?: null,
      powertonSeig?: null,
      daoSeig?: null,
      pseig?: null
    ): SeigGivenEventFilter;

    "SeigGiven2(address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)"(
      layer2?: PromiseOrValue<string> | null,
      totalSeig?: null,
      stakedSeig?: null,
      unstakedSeig?: null,
      powertonSeig?: null,
      daoSeig?: null,
      pseig?: null,
      l2TotalSeigs?: null,
      layer2Seigs?: null
    ): SeigGiven2EventFilter;
    SeigGiven2(
      layer2?: PromiseOrValue<string> | null,
      totalSeig?: null,
      stakedSeig?: null,
      unstakedSeig?: null,
      powertonSeig?: null,
      daoSeig?: null,
      pseig?: null,
      l2TotalSeigs?: null,
      layer2Seigs?: null
    ): SeigGiven2EventFilter;
  };

  estimateGas: {
    BURNT_AMOUNT_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    CHALLENGER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    INITIAL_TOTAL_SUPPLY_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_VALID_COMMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    RAY(overrides?: CallOverrides): Promise<BigNumber>;

    SEIG_START_MAINNET(overrides?: CallOverrides): Promise<BigNumber>;

    accRelativeSeig(overrides?: CallOverrides): Promise<BigNumber>;

    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    adjustCommissionDelay(overrides?: CallOverrides): Promise<BigNumber>;

    aliveImplementation(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    allowIssuanceLayer2Seigs(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burntAmountAtDAO(overrides?: CallOverrides): Promise<BigNumber>;

    dao(overrides?: CallOverrides): Promise<BigNumber>;

    daoSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    delayedCommissionBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delayedCommissionRate(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    delayedCommissionRateNegative(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    estimatedDistribute(
      blockNumber: PromiseOrValue<BigNumberish>,
      layer2: PromiseOrValue<string>,
      _isSenderOperator: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    excludeFromSeigniorage(
      _layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getOperatorAmount(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialTotalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    isAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    l2Registry(overrides?: CallOverrides): Promise<BigNumber>;

    l2RewardPerUint(overrides?: CallOverrides): Promise<BigNumber>;

    lastSnapshotId(overrides?: CallOverrides): Promise<BigNumber>;

    layer2Manager(overrides?: CallOverrides): Promise<BigNumber>;

    layer2RewardInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    layer2StartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    minimumAmount(overrides?: CallOverrides): Promise<BigNumber>;

    pauseProxy(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    powerTONSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    proxyImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    relativeSeigRate(overrides?: CallOverrides): Promise<BigNumber>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceChallenger(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceMinter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    seigStartBlock(overrides?: CallOverrides): Promise<BigNumber>;

    selectorImplementation(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setL2Registry(
      l2Registry_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLayer2Manager(
      layer2Manager_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLayer2StartBlock(
      startBlock_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalLayer2TVL(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyOfTon(overrides?: CallOverrides): Promise<BigNumber>;

    transferAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unSettledReward(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateSeigniorage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSeigniorageLayer(
      layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSeigniorageOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BURNT_AMOUNT_MAINNET(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CHALLENGER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INITIAL_TOTAL_SUPPLY_MAINNET(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_VALID_COMMISSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_VALID_COMMISSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSE_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RAY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SEIG_START_MAINNET(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accRelativeSeig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    adjustCommissionDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aliveImplementation(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allowIssuanceLayer2Seigs(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burntAmountAtDAO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dao(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daoSeigRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delayedCommissionBlock(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delayedCommissionRate(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    delayedCommissionRateNegative(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    estimatedDistribute(
      blockNumber: PromiseOrValue<BigNumberish>,
      layer2: PromiseOrValue<string>,
      _isSenderOperator: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    excludeFromSeigniorage(
      _layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOperatorAmount(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialTotalSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAdmin(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isChallenger(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMinter(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOperator(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l2Registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    l2RewardPerUint(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSnapshotId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    layer2Manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    layer2RewardInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    layer2StartBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minimumAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseProxy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    powerTONSeigRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxyImplementation(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    relativeSeigRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeAdmin(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceChallenger(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceMinter(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeChallenger(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeMinter(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeOperator(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    seigStartBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    selectorImplementation(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setL2Registry(
      l2Registry_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLayer2Manager(
      layer2Manager_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLayer2StartBlock(
      startBlock_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalLayer2TVL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupplyOfTon(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unSettledReward(
      layer2: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateSeigniorage(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSeigniorageLayer(
      layer2: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSeigniorageOperator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
