/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface L2RegistryV1_1StorageInterface extends utils.Interface {
  functions: {
    "rejectSystemConfig(address)": FunctionFragment;
    "seigniorageCommittee()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "rejectSystemConfig" | "seigniorageCommittee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "rejectSystemConfig",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "seigniorageCommittee",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "rejectSystemConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seigniorageCommittee",
    data: BytesLike
  ): Result;

  events: {};
}

export interface L2RegistryV1_1Storage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L2RegistryV1_1StorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    rejectSystemConfig(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    seigniorageCommittee(overrides?: CallOverrides): Promise<[string]>;
  };

  rejectSystemConfig(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  seigniorageCommittee(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    rejectSystemConfig(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    seigniorageCommittee(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    rejectSystemConfig(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seigniorageCommittee(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    rejectSystemConfig(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seigniorageCommittee(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
