/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IILayer2Registry } from "./IILayer2Registry";
export type { SeigManagerV1_Vote } from "./SeigManagerV1_Vote";
