/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositManager } from "./DepositManager";
export type { ILayer2 } from "./ILayer2";
export type { ILayer2Registry } from "./ILayer2Registry";
export type { IOnApprove } from "./IOnApprove";
export type { ISeigManager } from "./ISeigManager";
