/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DepositManagerForMigration } from "./DepositManagerForMigration";
export type { ILayer2 } from "./ILayer2";
export type { ILayer2Registry } from "./ILayer2Registry";
export type { IOldDepositManager } from "./IOldDepositManager";
export type { IOnApprove } from "./IOnApprove";
export type { ISeigManager } from "./ISeigManager";
