/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AutoRefactorCoinageI } from "./AutoRefactorCoinageI";
export type { CoinageFactoryI } from "./CoinageFactoryI";
export type { DepositManagerI } from "./DepositManagerI";
export type { IAutoCoinageSnapshot } from "./IAutoCoinageSnapshot";
export type { IIERC20 } from "./IIERC20";
export type { ILockTOSDividend } from "./ILockTOSDividend";
export type { IPowerTONSwapperEvent } from "./IPowerTONSwapperEvent";
export type { ITOS } from "./ITOS";
export type { RefactorCoinageSnapshotI } from "./RefactorCoinageSnapshotI";
export type { SeigManagerI } from "./SeigManagerI";
export type { SeigManagerV1I } from "./SeigManagerV1I";
export type { IPowerTON } from "./IPowerTON";
