/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DAOCommitteeOwnerTestBed } from "./DAOCommitteeOwnerTestBed";
export type { IPauser } from "./IPauser";
export type { ITarget } from "./ITarget";
