/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILayer2Candidate } from "./ILayer2Candidate";
export type { IOnDemandL2Registry } from "./IOnDemandL2Registry";
export type { Layer2CandidateFactory } from "./Layer2CandidateFactory";
